# Generated by Django 4.2 on 2023-05-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeriaWorks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('pizza_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeriaWorks.pizza')),
            ],
        ),
    ]
